FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -q
COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/click-tracker-backend-1.0.0.jar app.jar
COPY --from=build /app/src/main/resources/application.properties application.properties
EXPOSE 10000
ENTRYPOINT ["java", "-jar", "app.jar"]
