spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/click_tracker?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:@Kashsharma1}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=${PORT:8080}
spring.jackson.time-zone=Asia/Kolkata
