spring.datasource.url=jdbc:postgresql://db.tieroicjrtzhnqwyskrd.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Kashsharma123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=${PORT:10000}
spring.jackson.time-zone=Asia/Kolkata
