spring.datasource.url=${DATABASE_URL:jdbc:postgresql://db.tieroicjrtzhnqwyskrd.supabase.co:5432/postgres}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:@Kashsharma1}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=${PORT:8080}
spring.jackson.time-zone=Asia/Kolkata
